<form wire:submit="submitForm" class="bg-white rounded-2xl p-8 max-mobile:w-full max-mobile:min-w-0 border border-line shadow-[0_4px_24px_rgba(0,0,0,.06)]">
    <div class="mb-7"><p class="font-bold tracking-label uppercase mb-1 text-10 text-muted">NAPIŠTE NÁM</p><h2 class="font-condensed font-black uppercase leading-tight m-0 text-34">JAK VÁM MŮŽEME POMOCI?</h2></div>
    @if(session('message'))<p class="mb-4 rounded-lg bg-green-50 px-4 py-3 text-sm font-semibold text-success">{{ session('message') }}</p>@endif
    @if(session('error'))<p class="mb-4 rounded-lg bg-red-50 px-4 py-3 text-sm font-semibold text-red-600">{{ session('error') }}</p>@endif
    <div class="grid gap-4 mb-4 max-mobile:!grid-cols-1 grid-cols-[1fr_1fr]">
        <label class="flex flex-col gap-1.5"><span class="text-xs font-bold tracking-nav uppercase text-muted">Jméno a příjmení *</span><input wire:model="name" autocomplete="name" class="px-4 py-3 rounded-lg text-sm outline-none transition-all border-[1.5px] border-[#ddd9d3] font-sans focus-visible:outline focus-visible:outline-3 focus-visible:outline-orange focus-visible:outline-offset-3 focus:!border-orange-css focus:!outline focus:!outline-2 focus:!outline-orange-css focus:!outline-offset-1 focus:!shadow-none" required>@error('name')<span class="text-xs text-red-600">{{ $message }}</span>@enderror</label>
        <label class="flex flex-col gap-1.5"><span class="text-xs font-bold tracking-nav uppercase text-muted">E-mail *</span><input wire:model="email" autocomplete="email" type="email" class="px-4 py-3 rounded-lg text-sm outline-none transition-all border-[1.5px] border-[#ddd9d3] font-sans focus-visible:outline focus-visible:outline-3 focus-visible:outline-orange focus-visible:outline-offset-3 focus:!border-orange-css focus:!outline focus:!outline-2 focus:!outline-orange-css focus:!outline-offset-1 focus:!shadow-none" required>@error('email')<span class="text-xs text-red-600">{{ $message }}</span>@enderror</label>
    </div>
    <label class="flex flex-col gap-1.5 mb-4"><span class="text-xs font-bold tracking-nav uppercase text-muted">Předmět</span><select wire:model="subject" class="py-3 pl-4 pr-[2.6rem] rounded-lg text-sm outline-none appearance-none bg-no-repeat [background-position:right_1rem_center] [background-size:0.9rem] border-[1.5px] border-[#ddd9d3] font-sans text-nav-ink focus-visible:outline focus-visible:outline-3 focus-visible:outline-orange focus-visible:outline-offset-3 focus:!border-orange-css focus:!outline focus:!outline-2 focus:!outline-orange-css focus:!outline-offset-1 focus:!shadow-none bg-[url('/assets/obrazky/select-chevron.svg')]">
        <option>Obecný dotaz</option><option>Vstupenky</option><option>Partnerství</option><option>Média</option><option>Nábor hráčů</option>
    </select>@error('subject')<span class="text-xs text-red-600">{{ $message }}</span>@enderror</label>
    <label class="flex flex-col gap-1.5 mb-6"><span class="text-xs font-bold tracking-nav uppercase text-muted">Zpráva *</span><textarea wire:model="message" class="px-4 py-3 rounded-lg text-sm outline-none resize-none border-[1.5px] border-[#ddd9d3] font-sans focus-visible:outline focus-visible:outline-3 focus-visible:outline-orange focus-visible:outline-offset-3 focus:!border-orange-css focus:!outline focus:!outline-2 focus:!outline-orange-css focus:!outline-offset-1 focus:!shadow-none" rows="5" required></textarea>@error('message')<span class="text-xs text-red-600">{{ $message }}</span>@enderror</label>
    <div class="hidden" aria-hidden="true"><label>Web<input wire:model="website" type="text" tabindex="-1" autocomplete="off"></label></div>
    <button class="w-full cursor-pointer inline-flex items-center justify-center gap-2 font-condensed font-black text-sm tracking-widest uppercase px-6 py-4 rounded-lg text-white [transition:background_0.2s_ease,color_0.2s_ease,box-shadow_0.2s_ease,transform_0.2s_ease] bg-orange hover:!bg-wine hover:!text-white hover:shadow-[0_8px_20px_rgba(106,27,33,.28)] hover:-translate-y-px focus-visible:outline focus-visible:outline-3 focus-visible:outline-orange focus-visible:outline-offset-3 disabled:cursor-not-allowed disabled:opacity-60" type="submit" wire:loading.attr="disabled">
        <span wire:loading.remove>ODESLAT ZPRÁVU <span aria-hidden="true" class="font-condensed text-[1.03rem] leading-none">›</span></span><span wire:loading>ODESÍLÁM…</span>
    </button>
</form>
